# Generated by Django 5.1.1 on 2024-10-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_board_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
