# Generated by Django 4.2.16 on 2024-11-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_board_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
