# Generated by Django 4.2.16 on 2024-11-28 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_repost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repost',
            old_name='created_at',
            new_name='reposted_at',
        ),
    ]
