# Generated by Django 4.2.16 on 2024-11-28 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20241128_1100'),
    ]

    operations = [
    ]
